name: llama
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.7.4=hbcca054_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=14.1.0=h77fa898_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py310hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.5=h59595ed_0
  - openssl=3.3.1=h4ab18f5_1
  - python=3.10.14=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.29.2
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - anyio==4.4.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - bleach==6.1.0
      - brotli==1.0.9
      - build==1.2.1
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==2.0.4
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.30.0
      - colored==2.2.4
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.2.1
      - cuda-python==12.5.0
      - cycler==0.12.1
      - datasets==2.19.2
      - debugpy==1.6.7
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.14.0
      - defusedxml==0.7.1
      - diffusers==0.29.2
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.7.0
      - email-validator==2.2.0
      - entrypoints==0.4
      - evaluate==0.4.2
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - faiss-cpu==1.8.0.post1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.20.0
      - ffmpy==0.3.2
      - filelock==3.13.1
      - fonttools==4.53.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gmpy2==2.1.2
      - gradio==4.37.2
      - gradio-client==1.0.2
      - h11==0.14.0
      - h5py==3.10.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.2
      - humanfriendly==10.0
      - idna==3.4
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - intel-openmp==2024.1.0
      - interegular==0.3.3
      - ipykernel==6.29.3
      - ipython==8.22.2
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - janus==1.0.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lark==1.1.9
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.1
      - lomo-optim==0.1.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.6
      - maturin==1.7.0
      - mdurl==0.1.2
      - mistralrs-cuda==0.1.24
      - mistune==3.0.2
      - mkl==2024.1.0
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-modelopt==0.13.1
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.1
      - onnx-graphsurgeon==0.5.2
      - onnxruntime-genai-cuda==0.3.0
      - open-clip-torch==2.24.0
      - openai==1.35.10
      - opencv-python==4.10.0.84
      - optimum==1.21.4
      - orjson==3.10.6
      - outlines==0.0.46
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patchelf==0.17.2.1
      - peft==0.10.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==24.1.2
      - platformdirs==4.2.0
      - polygraphy==0.49.9
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.42
      - protobuf==4.25.3
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pulp==2.9.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pyav==13.0.0
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - qwen-vl-utils==0.0.4
      - ray==2.31.0
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - ruff==0.5.0
      - safetensors==0.4.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.2
      - starlette==0.37.2
      - strenum==0.4.15
      - sympy==1.12
      - tbb==2021.12.0
      - tensorboardx==2.6.2.2
      - tensorrt==10.2.0.post1
      - tensorrt-cu12==10.2.0.post1
      - tensorrt-cu12-bindings==10.2.0.post1
      - tensorrt-cu12-libs==10.2.0.post1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timm==1.0.7
      - tinycss2==1.3.0
      - tokenizers==0.20.0
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.2.0+cu121
      - torchaudio==2.2.0+cu121
      - torchvision==0.17.0+cu121
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.2
      - transformers==4.45.0
      - triton==2.2.0
      - trl==0.8.6
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.9.0
      - tyro==0.8.4
      - tzdata==2024.1
      - ujson==5.10.0
      - uri-template==1.3.0
      - urllib3==2.1.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - wandb==0.16.6
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - widgetsnbextension==4.0.11
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.19.2
